[package]
name = "subscription-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.subscription]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.0"
default-features = false
